import type { Metadata } from "next";
import { Inter } from "next/font/google";
import SecNav from "@/components/secNav/SecNav";
import Background from "@/components/Background";
import Complain from "@/components/Complain";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SecNav />
        <div className="h-screen w-screen flex items-center relative">
          <Background />
          {children}
        </div>
        <Complain />
      </body>
    </html>
  );
}
